pull_request_rules:
  - name: Automatic merge when approved by Jimmy
    conditions:
      - "approved-reviews-by=rootsongjc"
      - "#approved-reviews-by>=1"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Automatic merge when approved by zhangguanzhang
    conditions:
      - "approved-reviews-by=zhangguanzhang"
      - "#approved-reviews-by>=1"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Automatic merge when approved by lhb008
    conditions:
      - "approved-reviews-by=lhb008"
      - "#approved-reviews-by>=1"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}?
